### ISSUE TITLE
It dosen't load lol

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [Mr-funkinguy/FNF-NEO-HTML5-BY-ME#1]

**Comment by Mr-funkinguy** [comment]
Its In Progress

**Comment by LEVIXDDLMAO** [comment]
when do you think it will be done

**Comment by Mr-funkinguy** [comment]
in a few mins
btw if your gonna use Test it bc i want feed back (:

**Comment by LEVIXDDLMAO** [comment]
Thats what i wanna do :D

**Comment by Mr-funkinguy** [comment]
Its Ready (:

**Comment by LEVIXDDLMAO** [comment]
It works really good! oh and can you port tails.exe? you dont have too lol

**Comment by Mr-funkinguy** [comment]
Ill TRy

**Comment by LEVIXDDLMAO** [comment]
Thx! the source should be there on github

**Comment by Mr-funkinguy** [comment]
ye

**Comment by LEVIXDDLMAO** [comment]
Do you want the link?

**Comment by Mr-funkinguy** [comment]
Sure If You Want To Link It

**Comment by LEVIXDDLMAO** [comment]
Okay

**Comment by LEVIXDDLMAO** [comment]
https://github.com/iamteles/VS-Tails.EXE-Source

**Comment by LEVIXDDLMAO** [comment]
did it work??

**Comment by Mr-funkinguy** [comment]
Im Working on it

**Comment by LEVIXDDLMAO** [comment]
Ah sorry i dont mean to sound like im rushing you

**Comment by Mr-funkinguy** [comment]
no no its ok

**Comment by LEVIXDDLMAO** [comment]
oh and im a big fan of your work

**Comment by Mr-funkinguy** [comment]
thanks (:

**Comment by LEVIXDDLMAO** [comment]
np!

**Comment by Mr-funkinguy** [comment]
https://mr-funkinguy.github.io/FNF-NEO-HTML5-BY-ME/
(This Is Just If You Want To Link OR Som idk

**Comment by LEVIXDDLMAO** [comment]
yeah i have a google doc with fnf links lol

**Comment by Mr-funkinguy** [comment]
can i have da link lol
i wanna see your work

**Comment by LEVIXDDLMAO** [comment]
most of my work is on github like i have sonic exe psych engine v2

**Comment by Mr-funkinguy** [comment]
ooooo

**Comment by LEVIXDDLMAO** [comment]
Yep ^^

**Comment by LEVIXDDLMAO** [comment]
https://levixddlmao.github.io/Sonic.exeHTML5/

**Comment by LEVIXDDLMAO** [comment]
https://levixddlmao.github.io/Tabi_rework_html5/

**Comment by LEVIXDDLMAO** [comment]
those are my main favs

**Comment by LEVIXDDLMAO** [comment]
Any errors

**Comment by Mr-funkinguy** [comment]
not yet like i said im Am God (:

**Comment by LEVIXDDLMAO** [comment]
XD
